# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: simon.woerpel@medienrevolte.de
description: > # this means to ignore newlines until "baseurl:"
  homepage and blog from simon wörpel, data journalist and newsroom hacker at correctiv.org
title: simon wörpel
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
twitter_username: simonwoerpel
github_username:  simonwoerpel

permalink: pretty

# Build settings
markdown: kramdown
# theme: jekyll-mr-theme

source: "./_src"
destination: "./docs"

sass:
  style: compressed


defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      show_menu: true
      permalink: /:path/:basename/
      layout: page
  -
    scope:
      type: projects
    values:
      layout: project


collections:
    projects:
      output: true
